### PR TITLE
Using MainWindow instead of SDL_Renderer_ctx

### PR DESCRIPTION
**Pull request by TedLyngmo**
Removed `static` variables from `MainWindow` now that it's passed to its children.

Also added support for caching textures

---
This is the start of what I was working on. I haven't made use of the caching functionality everywhere but `Button` and `Image` uses it so the `Button.png` surface is only loaded once and three different textures are created from it:
```c++
enum { textureInactive, textureIdle, textureHoovered };
std::array<TextureRef, 3> textures;
TextureRef active_texture{textures[textureIdle]};
```
In the code, it's just a matter of doing `active_texture = textures[textureHoovered];` and it will swap to the hoovered state without calling any functions/loading anything.

I'd like to cache the text textures too, but only if this first thing with the loadable images works out. All AddressSanitizer-runs are clean so it looks good.

### CODE REVIEW

**Comment by PanosPetras** [comment]
I see that there is a conflict, should I try to resolve it? I'm afraid I might up something that you are trying to do. Btw, can't we skip the passing around `MainWindow` references part since it is a singleton?

**Comment by TedLyngmo** [comment]
> I see that there is a conflict

Yes, I started the work from fd6cafa1949bb563e7678d6312724be088c9b07c so I didn't have the `War` additions and the following changed you made. I cherry-picked the `War` commit though and corrected a few mistakes when it comes to initialization.

> should I try to resolve it? I'm afraid I might up something that you are trying to do.

There are now two separate tracks. I'm not sure if resolving the conflicts would lead to anything useful but we can take a look at it.

In the branch I've made, there are no `share_ptr` and the RAII classes in `SDL_ctx.h` are still pretty much simple wrappers around a raw pointer. I'd personally try to keep those clean of caching logic and instead build that into some resource manager, like `MainWindow` (which could perhaps be renamed if _Window_ doesn't seem appropriate anymore).

> Btw, can't we skip the passing around `MainWindow` references part since it is a singleton?

Singleton or not, keeping a reference to the `MainWindow` in the children isn't much different from keeping a reference to the `SDL_Renderer_ctx` that is owned by the main window. The only difference that I can see is that using the main window allows us to use it as a resource manager. Taking a reference to the main window in the constructor of the children also made it possible to remove the `static` windows dimensions that I had to use to not get a deadlock when creating the main window. It actually makes it pssible to make `MainWindow` into a non-singleton again. There is only one call to `MainWindow::Instance()` left and that's one that I forgot to remove from `Button`. When that's removed, it can be thought of like just any class.

**Comment by TedLyngmo** [comment]
I'll abandon this PR later. I made https://github.com/PanosPetras/The_Great_War/pull/16 which has the commits in the correct order.

**Comment by TedLyngmo** [comment]
Handled in a different patch

**Pull request closed without merging**
