### PR TITLE
Replace CountryBalances.txt with CountryStockpiles.txt

### PR DESCRIPTION
**Pull request by TedLyngmo**
Fixes https://github.com/PanosPetras/The_Great_War/issues/24

### CODE REVIEW

**Comment by PanosPetras** [comment]
I'm going to check it out tomorrow.

**Comment by PanosPetras** [comment]
Yep, it's still zoomed in.

**Comment by PanosPetras** [comment]
Merge what you think is ready to be merged because i don't know if you think it's ready or not. I am watching the changes that are made in the commit history.

**Comment by TedLyngmo** [comment]
@PanosPetras They are all ready to be merged but since I don't know what's making that zoom effect on your side, I don't dare. Oh well, I'll merge one and you can see if it affects the zoom.

**Pull request merged**
