### PR TITLE
Use std::jthread

### PR DESCRIPTION
**Pull request by TedLyngmo**
There are currently three extra threads started by the application. None do synchronization between the threads so there are race conditions.

I've replaced the threads with `std::jthread`s which can be used to start a thread in a member function (unlike `SDL_CreateThread`).

`bIsPaused` is made into a `std::atomic<bool>` and moved out of the `Date` struct.

No further synchronization work has been done - but it's needed.

### CODE REVIEW

**Comment by PanosPetras** [comment]
This is fine. There is no zoom bug. I do get a warning when building though.

> C:\Users\\...\The_Great_War\Eater.h(31): warning C6287: Redundant code.

I will merge this to master.

**Comment by TedLyngmo** [comment]
Lovely! One down! :-)

**Comment by TedLyngmo** [comment]
> I do get a warning when building though.
> 
> > C:\Users\...\The_Great_War\Eater.h(31): warning C6287: Redundant code.

I just took a look at that. That's an utterly strange warning since the function will not work without that code :-)

**Comment by PanosPetras** [comment]
Then don't worry about it, it does not look like something important anyways.

**Pull request merged**
