### PR TITLE
Use mainwindow ref

### PR DESCRIPTION
**Pull request by TedLyngmo**

### CODE REVIEW

**Comment by TedLyngmo** [comment]
Here's better version with the commits in the correct order.

**Comment by PanosPetras** [comment]
I have realized that you are correct in wanting to keep all the context classes as simple wrappers. I will thus revert the changes that i have made.

**Comment by PanosPetras** [comment]
Can you please resolve the conflicts by discarding the changes that i have made on master? I don't know how do it haha.

**Review by PanosPetras — APPROVED** [review]
Looks good to me.

**Pull request merged**
