### PR TITLE
Revert "Replace CountryBalances.txt with CountryStockpiles.txt"

### PR DESCRIPTION
**Pull request by TedLyngmo**
This reverts commit 26c48aaac82473226e488bcaf15cafc29e8c583e.

If the current commit on master affects the zoom, just merge this commit. It should restore it.

### CODE REVIEW

**Comment by TedLyngmo** [comment]
@PanosPetras  I've finally setup my Windows environment to try to see if I can find the reason for the zooming strangeness but for me it looks perfectly fine. It's nice to finally hear the sounds too :-)

**Comment by PanosPetras** [comment]
That's Great!

**Comment by TedLyngmo** [comment]
> I think we should fix the bug before we merge. What do you think is best?

Yes, that's probably best. So, it's working on master right now, even with the Stockpiles change?

**Comment by PanosPetras** [comment]
> So, it's working on master right now, even with the Stockpiles change?
Yes it is. I am running it right now on my computer.

**Comment by TedLyngmo** [comment]
Ok great! In that case, I'm closing this revert PR.

**Pull request closed without merging**
