### PR TITLE
Add `MIX_Chunk_ctx` and improve threading

### PR DESCRIPTION
**Pull request by TedLyngmo**

### CODE REVIEW

**Comment by TedLyngmo** [comment]
@PanosPetras It'd be great if you could download this branch again and then checkout try the first commit (` Add MIX_Chunk_ctx`) to verify that it still causes problems with zooming.

**Comment by PanosPetras** [comment]
Yep it pretty has the same bug. It is very peculiar.

**Comment by TedLyngmo** [comment]
> Yep it pretty has the same bug. It is very peculiar.

And it's the same even if you try the different commits separately?

I will try to break it down in smaller bits - if that's even possible :-)

**Comment by PanosPetras** [comment]
I went as far back as commit [18d86d0](https://github.com/TedLyngmo/The_Great_War/commit/18d86d01b3359be3b04b77de5d64edc6086a89fc) in the branch `TedLyngmo:mix_chunk_and_race` and i still have the same issue.

**Comment by PanosPetras** [comment]
Still there in commit [b498688](https://github.com/TedLyngmo/The_Great_War/commit/b498688f587fd8c6e1a614a86cd23ed3dd64179e)

**Comment by PanosPetras** [comment]
I tried downloading the master branch again just in case the problem was always present and there was something wrong with my copy of the branch. It works just fine.

**Comment by PanosPetras** [comment]
I also tried `TedLyngmo:master` and it works fine.

**Comment by TedLyngmo** [comment]
Great. You only need to check the two commits ahead of your `master` branch though.

`TedLyngmo:master` is usually a mirror of your `master`. That's what I use when I synchronize different branches on my side and don't want anything you do to `master` to have an effect on that. As soon as my work is done, it'll be in perfect sync with your `master` again, so there's no need checking that. :)

But, you are positive it's not a problem on the current `master` commit?

**Comment by PanosPetras** [comment]
> But, you are positive it's not a problem on the current `master` commit?

Yes, I'm 100% certain of that.

**Comment by TedLyngmo** [comment]
I'm closing this since I've separated the two commits again.

**Pull request closed without merging**
